salesforce_sis/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

salesforce_sis/force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce_sis/force-app/main/default/objects/Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce_sis/force-app/main/default/objects/Enrollment__c/fields/Letter_Grade__c.field-meta.xml
<CustomField>
    <fullName>Letter_Grade__c</fullName>
    <formula>IF(ISBLANK(Grade_Points__c), null,
IF(Grade_Points__c &gt;= 90, &quot;A&quot;,
IF(Grade_Points__c &gt;= 80, &quot;B&quot;,
IF(Grade_Points__c &gt;= 70, &quot;C&quot;,
IF(Grade_Points__c &gt;= 60, &quot;D&quot;,
&quot;F&quot;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Letter Grade</label>
    <type>Text</type>
</CustomField>

salesforce_sis/force-app/main/default/classes/GradeDistributionController.cls
public with sharing class GradeDistributionController {
    @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getGradeDistribution(Id courseId) {
        Map<String, Integer> distribution = new Map<String, Integer>{
            'A' => 0, 'B' => 0, 'C' => 0, 'D' => 0, 'F' => 0
        };

        List<Enrollment__c> enrollments = [
            SELECT Letter_Grade__c 
            FROM Enrollment__c 
            WHERE Course__c = :courseId
            AND Letter_Grade__c != null
        ];

        for (Enrollment__c e : enrollments) {
            if (distribution.containsKey(e.Letter_Grade__c)) {
                distribution.put(e.Letter_Grade__c, distribution.get(e.Letter_Grade__c) + 1);
            }
        }
        return distribution;
    }
}